<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyName>OverlayCompareTool</AssemblyName>
    <Product>Overlay Compare Tool</Product>
    <Version>1.0.1</Version>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Resources\OCT.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFtoImage" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\OCT.ico" />
    <Resource Include="Resources\Bluemoose.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Demo_Rev A.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Demo_Rev B.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>